### Recover all movies 

GET http://localhost:3312/movies

### Recover movies for id
GET http://localhost:3312/movies/c906673b-3948-4402-ac7f-73ac3a9e3105

### Recover all movis for gender
GET http://localhost:3312/movies?gender=Action

